### ISSUE TITLE
Mark's 24h maintenance tracker

### ISSUE THREAD

**Issue by SharpRake** [chainguard-dev/edu#1716]
**Description:**
I've got a bunch of small maintenance-type tasks built up. I'm going to spend time in 24h tackling them. This issue is track the overall work:

- [x] [Academy updates around console.chainguard.dev entitlement tracking updates](https://github.com/chainguard-dev/internal/issues/3839)
- [x] [Update Debugging Distroless Guide](https://github.com/chainguard-dev/internal/issues/4043)
- [x] [Academy docs: replace/remove references to console.enforce.dev with console.chainguard.dev](https://github.com/chainguard-dev/internal/issues/4073)
- [x] [Investigate old/broken links](https://github.com/chainguard-dev/edu/issues/1715)
- [x] ["inky" --> "linky"](https://github.com/chainguard-dev/internal/issues/4103)
- [x] [Readme Prioritization](https://github.com/chainguard-dev/internal/issues/4052)

**Comment by SharpRake** [comment]
I'm picking these off slowly, My next focus will be on documenting the `--headless` feature

**Comment by SharpRake** [comment]
README prioritization is ongoing, although this did get my attention over 24h. Closing this issue for end of cycle.
